name: Deploy to Render

on:
  push:
    branches:
      - main  # or 'master', whichever your main branch is

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST https://api.render.com/deploy/srv-d209ud7fte5s738kv0jg?key=hkdLUaD7DkI
